version: '3.8'
services:
  elasticsearch:
    image: 'elasticsearch:7.11.1'
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - '0.0.0.0:9200:9200'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types= inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 5s
      timeout: 10s
      retries: 20
    volumes:
      - e-data:/usr/share/elasticsearch/data
      - e-logs:/usr/share/elasticsearch/logs

  cortex:
    image: 'thehiveproject/cortex:latest'
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - job_directory=${job_directory:-/tmp/job-directory}
      - start_docker=0
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${job_directory:-/tmp/job-directory}:${job_directory:-/tmp/job-directory}'
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - '0.0.0.0:9001:9001'

  thehive:
    image: strangebee/thehive:5.2
    platform: linux/amd64
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto
      - LANG=C.UTF-8
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - '0.0.0.0:9000:9000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://thehive:9000"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - t-data:/opt/thp
    command: "--cortex-keys $CORTEX_KEY --cortex-port 9001"

  splunk:
    extends:
      file: ./configs/docker/splunk.yml
      service: so1
    environment:
      - SPLUNK_APPS_URL=https://github.com/LetMeR00t/TA-thehive-cortex/releases/download/v3.3/TA-thehive-cortex-3.3.spl
    volumes:
      - $PWD/app:/opt/splunk/etc/apps/cortex-s2


  splunk-init:
    build: ./configs/docker/
    platform: linux/amd64
    environment:
      - CORTEX_USER=${CORTEX_USER:-cortex-user}
      - CORTEX_PASSWORD=${CORTEX_PASSWORD:-changeme2}
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD:-changeme}
    depends_on:
      splunk:
        condition: service_healthy
        restart: true

volumes:
  e-data: {}
  e-logs: {}
  t-data: {}
  
